# Setup
title:        DragonRuby Dispatch
description:  Tales from the Dragon
baseurl:      ""
url: "https://dragonrubydispatch.com"
paginate:     10
locale:       "en"
google_analytics: UA-37342921-5

# About/contact
author:
  name: Lori M Olson
  url: https://wndx.school

# Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman

github: [metadata]
