# Setup
title:        RubyMotion Weekly
description:  Tales from the Dragon
baseurl:      ""
url: "https://rubymotionweekly.com"
paginate:     10
locale:       "en"

# About/contact
author:
  name: Lori Olson
  url: https://wndx.school

# Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman

github: [metadata]
